import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const HEADER_COMMENT = `/* eslint-disable */
// This file is auto-generated by npm run codegen. Do not edit manually.`;

/** @type {import("@graphql-codegen/cli").CodegenConfig} */
const config = {
  overwrite: true,
  schema: [
    // AppSync custom scalar declarations (not defined in the schema file itself)
    `scalar AWSJSON
     scalar AWSDateTime
     scalar AWSDate
     scalar AWSTimestamp
     scalar AWSTime
     scalar AWSURL
     scalar AWSEmail
     scalar AWSPhone
     scalar AWSIPAddress`,
    path.resolve(__dirname, "../../nested/appsync/src/api/schema.graphql"),
  ],
  documents: path.resolve(__dirname, "src/graphql/operations/**/*.graphql"),
  config: {
    skipTypename: true,
    enumsAsTypes: true,
    scalars: {
      AWSJSON: "string",
      AWSDateTime: "string",
      AWSDate: "string",
      AWSTimestamp: "number",
      AWSTime: "string",
      AWSURL: "string",
      AWSEmail: "string",
      AWSPhone: "string",
      AWSIPAddress: "string",
    },
  },
  generates: {
    [path.resolve(__dirname, "src/graphql/generated/schema-types.ts")]: {
      plugins: [
        { add: { content: HEADER_COMMENT } },
        "typescript",
      ],
    },
    [path.resolve(__dirname, "src/graphql/generated/operation-types.ts")]: {
      plugins: [
        { add: { content: HEADER_COMMENT } },
        "typescript",
        "typescript-operations",
      ],
    },
  },
};

export default config;
