query GetDocument($objectKey: ID!) {
  getDocument(ObjectKey: $objectKey) {
    ObjectKey
    ObjectStatus
    InitialEventTime
    QueuedTime
    WorkflowStartTime
    CompletionTime
    WorkflowExecutionArn
    WorkflowStatus
    PageCount
    Sections {
      Id
      PageIds
      Class
      OutputJSONUri
      Excluded
      ExclusionReason
      ConfidenceThresholdAlerts {
        attributeName
        confidence
        confidenceThreshold
      }
      ProcessingIssues {
        stage
        severity
        code
        message
        rootCause
      }
    }
    Pages {
      Id
      Class
      ImageUri
      TextUri
      TextConfidenceUri
      OcrPageDataUri
    }
    Metering
    EvaluationReportUri
    EvaluationStatus
    SummaryReportUri
    RuleValidationResultUri
    ExpiresAfter
    HITLStatus
    HITLTriggered
    HITLReviewURL
    HITLSectionsPending
    HITLSectionsCompleted
    HITLSectionsSkipped
    HITLReviewOwner
    HITLReviewOwnerEmail
    HITLReviewedBy
    HITLReviewedByEmail
    HITLReviewHistory
    ConfigVersion
    HITLCompleted
    ProcessingIssueCount
    TraceId
  }
}
